---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: example-kubeconfig
  namespace: default
spec:
  filterTags:
    extract: $ts
    pattern: ^dev-branch-[a-f0-9]+-(?P<ts>[0-9]+)
  imageRepositoryRef:
    name: howto-kubeconfig-dev
  policy:
    numerical:
      order: asc

