apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-kubeconfig
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: example-kubeconfig-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: example-kubeconfig-nginx
    spec:
      initContainers:
      - name: flux-pull
        image: img.hephy.pro/examples/howto-kubeconfig:serve
        imagePullPolicy: Always
        command:
          - "/usr/local/bin/flux-pull.sh"
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: html
        env:
          - name: CONTENT_HASH
            valueFrom:
              configMapKeyRef:
                name: site-content
                key: content-hash

      containers:
      - name: nginx
        image: img.hephy.pro/examples/howto-kubeconfig:serve # build
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: html
      volumes:
      - name: html
        emptyDir:
          sizeLimit: 100Mi
