apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- content-hash.yaml
- reloader/
images:
- name: img.hephy.pro/examples/howto-kubeconfig
  newName: img.hephy.pro/examples/howto-kubeconfig
  newTag: serve
